#!/bin/bash

random_num() {
    local beg=1
    local end=100
    echo $((RANDOM % (end - beg + 1) + beg))
}
x=$(random_num)
while true; do
    echo -n "Enter a guess: "
    read guess

    if ! [[ "$guess" =~ ^[0-9]+$ ]]; then
        echo "Erorr: enter an integer!"
        continue
    fi
    if [ "$guess" -lt 1 ] || [ "$guess" -gt 100 ]; then
        echo "1 to 100"
        continue
    fi

    if [ "$guess" -lt "$x" ]; then
        echo "The number is greater"
    elif [ "$guess" -gt "$x" ]; then
        echo "The number is less"
    else
        echo "You guessed the number $x!"
        break
    fi
done
